/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AssuranceVol {
  export type BilletStruct = {
    id: BigNumberish;
    acheteur: AddressLike;
    prixEnWei: BigNumberish;
    dureeVol: BigNumberish;
    statut: BigNumberish;
  };

  export type BilletStructOutput = [
    id: bigint,
    acheteur: string,
    prixEnWei: bigint,
    dureeVol: bigint,
    statut: bigint
  ] & {
    id: bigint;
    acheteur: string;
    prixEnWei: bigint;
    dureeVol: bigint;
    statut: bigint;
  };
}

export interface AssuranceVolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "billets"
      | "compteurBillets"
      | "constaterRetard"
      | "getBillet"
      | "payerBillet"
      | "proprietaire"
      | "retirerFonds"
      | "setTauxConversion"
      | "souscrireAssurance"
      | "tauxConversionEthEur"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssuranceActivee"
      | "BilletSouscrit"
      | "FondsRetires"
      | "RemboursementEffectue"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "billets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "compteurBillets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "constaterRetard",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBillet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payerBillet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proprietaire",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retirerFonds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTauxConversion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "souscrireAssurance",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tauxConversionEthEur",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "billets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "compteurBillets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "constaterRetard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBillet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payerBillet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proprietaire",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retirerFonds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTauxConversion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "souscrireAssurance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tauxConversionEthEur",
    data: BytesLike
  ): Result;
}

export namespace AssuranceActiveeEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BilletSouscritEvent {
  export type InputTuple = [
    id: BigNumberish,
    acheteur: AddressLike,
    prixEnWei: BigNumberish,
    dureeVol: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    acheteur: string,
    prixEnWei: bigint,
    dureeVol: bigint
  ];
  export interface OutputObject {
    id: bigint;
    acheteur: string;
    prixEnWei: bigint;
    dureeVol: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FondsRetiresEvent {
  export type InputTuple = [montant: BigNumberish];
  export type OutputTuple = [montant: bigint];
  export interface OutputObject {
    montant: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemboursementEffectueEvent {
  export type InputTuple = [id: BigNumberish, montantRembourse: BigNumberish];
  export type OutputTuple = [id: bigint, montantRembourse: bigint];
  export interface OutputObject {
    id: bigint;
    montantRembourse: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssuranceVol extends BaseContract {
  connect(runner?: ContractRunner | null): AssuranceVol;
  waitForDeployment(): Promise<this>;

  interface: AssuranceVolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  billets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        acheteur: string;
        prixEnWei: bigint;
        dureeVol: bigint;
        statut: bigint;
      }
    ],
    "view"
  >;

  compteurBillets: TypedContractMethod<[], [bigint], "view">;

  constaterRetard: TypedContractMethod<
    [_billetId: BigNumberish, _retardEnHeures: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBillet: TypedContractMethod<
    [_billetId: BigNumberish],
    [AssuranceVol.BilletStructOutput],
    "view"
  >;

  payerBillet: TypedContractMethod<
    [_billetId: BigNumberish],
    [void],
    "payable"
  >;

  proprietaire: TypedContractMethod<[], [string], "view">;

  retirerFonds: TypedContractMethod<
    [_montant: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTauxConversion: TypedContractMethod<
    [_nouveauTaux: BigNumberish],
    [void],
    "nonpayable"
  >;

  souscrireAssurance: TypedContractMethod<
    [_dureeVol: BigNumberish, _prixEnEur: BigNumberish],
    [void],
    "nonpayable"
  >;

  tauxConversionEthEur: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "billets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        acheteur: string;
        prixEnWei: bigint;
        dureeVol: bigint;
        statut: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "compteurBillets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "constaterRetard"
  ): TypedContractMethod<
    [_billetId: BigNumberish, _retardEnHeures: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBillet"
  ): TypedContractMethod<
    [_billetId: BigNumberish],
    [AssuranceVol.BilletStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "payerBillet"
  ): TypedContractMethod<[_billetId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "proprietaire"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "retirerFonds"
  ): TypedContractMethod<[_montant: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTauxConversion"
  ): TypedContractMethod<[_nouveauTaux: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "souscrireAssurance"
  ): TypedContractMethod<
    [_dureeVol: BigNumberish, _prixEnEur: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tauxConversionEthEur"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AssuranceActivee"
  ): TypedContractEvent<
    AssuranceActiveeEvent.InputTuple,
    AssuranceActiveeEvent.OutputTuple,
    AssuranceActiveeEvent.OutputObject
  >;
  getEvent(
    key: "BilletSouscrit"
  ): TypedContractEvent<
    BilletSouscritEvent.InputTuple,
    BilletSouscritEvent.OutputTuple,
    BilletSouscritEvent.OutputObject
  >;
  getEvent(
    key: "FondsRetires"
  ): TypedContractEvent<
    FondsRetiresEvent.InputTuple,
    FondsRetiresEvent.OutputTuple,
    FondsRetiresEvent.OutputObject
  >;
  getEvent(
    key: "RemboursementEffectue"
  ): TypedContractEvent<
    RemboursementEffectueEvent.InputTuple,
    RemboursementEffectueEvent.OutputTuple,
    RemboursementEffectueEvent.OutputObject
  >;

  filters: {
    "AssuranceActivee(uint256)": TypedContractEvent<
      AssuranceActiveeEvent.InputTuple,
      AssuranceActiveeEvent.OutputTuple,
      AssuranceActiveeEvent.OutputObject
    >;
    AssuranceActivee: TypedContractEvent<
      AssuranceActiveeEvent.InputTuple,
      AssuranceActiveeEvent.OutputTuple,
      AssuranceActiveeEvent.OutputObject
    >;

    "BilletSouscrit(uint256,address,uint256,uint256)": TypedContractEvent<
      BilletSouscritEvent.InputTuple,
      BilletSouscritEvent.OutputTuple,
      BilletSouscritEvent.OutputObject
    >;
    BilletSouscrit: TypedContractEvent<
      BilletSouscritEvent.InputTuple,
      BilletSouscritEvent.OutputTuple,
      BilletSouscritEvent.OutputObject
    >;

    "FondsRetires(uint256)": TypedContractEvent<
      FondsRetiresEvent.InputTuple,
      FondsRetiresEvent.OutputTuple,
      FondsRetiresEvent.OutputObject
    >;
    FondsRetires: TypedContractEvent<
      FondsRetiresEvent.InputTuple,
      FondsRetiresEvent.OutputTuple,
      FondsRetiresEvent.OutputObject
    >;

    "RemboursementEffectue(uint256,uint256)": TypedContractEvent<
      RemboursementEffectueEvent.InputTuple,
      RemboursementEffectueEvent.OutputTuple,
      RemboursementEffectueEvent.OutputObject
    >;
    RemboursementEffectue: TypedContractEvent<
      RemboursementEffectueEvent.InputTuple,
      RemboursementEffectueEvent.OutputTuple,
      RemboursementEffectueEvent.OutputObject
    >;
  };
}
