/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AssuranceVol__factory } from "./AssuranceVol__factory";
export { Counter__factory } from "./Counter__factory";
